name: Bug report
description: Report a reproducible bug
title: "bug: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
