name: Feature request
description: Propose a new feature
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
